name: Docker CI

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        include:
          - context: frontend
            image: frontend
          - context: backend
            image: backend
          - context: vidbackend
            image: backendvid

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.image }} Docker image
        run: |
          IMAGE_NAME=${{ matrix.image }}
          IMAGE_TAG=$(date +%s)
          docker build ${{ matrix.context }} --file ${{ matrix.context }}/Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
